VueByAspNet_Mvc/Controllers/DemoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace VueByAspNet_Mvc.Controllers
{
    public class DemoController : Controller
    {
        // GET: Demo
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// toDoList
        /// </summary>
        /// <returns></returns>
        public ActionResult toDoList()
        {
            return View();
        }
        
    }
}

VueByAspNet_Mvc/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace VueByAspNet_Mvc.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

VueByAspNet_Mvc/Views/Demo/toDoList.cshtml
@{
    ViewBag.Title = "計畫表";
}

<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title - 我的 ASP.NET 應用程式</title>
</head>
<body>
    <div>
        @*須將Vue註冊的ID綁定HTML*@
        <div class="container flex" id="TodoListView">
            <!--未完成表格 -->
            <div class="col-lg-12 com-xs-12">
                <div class="table-responsive-vertical shadow-z-1">
                    <table class="table table-bordered table-mc-indigo table-hover" id="notFinfshTable">
                        <caption style="color:red">未完成</caption>
                        <thead class="bg-danger">
                            <tr>
                                <th>序號</th>
                                <th>標題</th>
                                <th>內容</th>
                                <th>開始日期</th>
                                <th>結束日期</th>
                            </tr>
                        </thead>
                        <tbody v-for="(item,index) in notFinishDataList" :key="index">
                            <tr>
                                <td data-title="序號" style="display:table-cell; vertical-align:middle">{{index+1}}</td>
                                <td data-title="標題" style="display:table-cell; vertical-align:middle">{{item.myTitle}}</td>
                                <td data-title="內容" style="display:table-cell; vertical-align:middle">{{item.myDetail}}</td>
                                <td data-title="開始日期" style="display:table-cell; vertical-align:middle">{{item.myStartDate}}</td>
                                <td data-title="結束日期" style="display:table-cell; vertical-align:middle">{{item.myDueDate}}</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div><!--未完成表格End -->
             <!--進行中表格 -->
            <div class="col-lg-12 com-xs-12">
                <div class="table-responsive-vertical shadow-z-1">
                    <table class="table table-bordered table-mc-indigo table-hover" id="DoingTable">
                        <caption style="color:sandybrown">進行中</caption>
                        <thead class="bg-warning">
                            <tr>
                                <th>序號</th>
                                <th>標題</th>
                                <th>內容</th>
                                <th>開始日期</th>
                                <th>結束日期</th>
                            </tr>
                        </thead>
                        <tbody v-for="(item,index) in DoingDataList" :key="index">
                            <tr>
                                <td data-title="序號" style="display:table-cell; vertical-align:middle">{{index+1}}</td>
                                <td data-title="標題" style="display:table-cell; vertical-align:middle">{{item.myTitle}}</td>
                                <td data-title="內容" style="display:table-cell; vertical-align:middle">{{item.myDetail}}</td>
                                <td data-title="開始日期" style="display:table-cell; vertical-align:middle">{{item.myStartDate}}</td>
                                <td data-title="結束日期" style="display:table-cell; vertical-align:middle">{{item.myDueDate}}</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div><!--進行中表格End -->
             <!--已完成表格 -->
            <div class="col-lg-12 com-xs-12">
                <div class="table-responsive-vertical shadow-z-1">
                    <table class="table table-bordered table-mc-indigo table-hover" id="isFinfshTable">
                        <caption style="color:blue">已完成</caption>
                        <thead class="bg-primary">
                            <tr>
                                <th>序號</th>
                                <th>標題</th>
                                <th>內容</th>
                                <th>開始日期</th>
                                <th>結束日期</th>
                            </tr>
                        </thead>
                        <tbody v-for="(item,index) in isFinishDataList" :key="index">
                            <tr>
                                <td data-title="序號" style="display:table-cell; vertical-align:middle">{{index+1}}</td>
                                <td data-title="標題" style="display:table-cell; vertical-align:middle">{{item.myTitle}}</td>
                                <td data-title="內容" style="display:table-cell; vertical-align:middle">{{item.myDetail}}</td>
                                <td data-title="開始日期" style="display:table-cell; vertical-align:middle">{{item.myStartDate}}</td>
                                <td data-title="結束日期" style="display:table-cell; vertical-align:middle">{{item.myDueDate}}</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div><!--已完成表格End -->
        </div>
    </div>

    @*1.引用JS*@
    <script src="~/Scripts/vue.js"></script>
    <script src="~/Scripts/jquery-3.3.1.js"></script>
    <script src="~/Scripts/sweetalert2.all.min.js"></script>
    <script>

        //先實例化一個vue
        var vueApp = new Vue({
            el: "#TodoListView",//範圍宣告需對應到Html會被作用到的id
            //定義物件
            data: {
                //畫面上所需要用的陣列
                dataList: [],
            },
            //init畫面建立DOM生成前就執行(使用:created)
            //init畫面建立DOM生成後才執行(使用:mounted)
            mounted() {
                //在畫面建立的時候需要呼叫方法到後端要資料
                _self = this;
                //在Vue要使用變數都須加上this指向自己
                _self.getData();

            },
            //所有方法都寫在Methods中
            methods: {

                //生成畫面資料
                getData: function () {
                    _self = this;
                    //先將資料寫死在畫面
                    //將資料寫入date1陣列中(未完成資料)
                    let date1 = {
                        myTitle: "學習api",
                        myDetail: "使用api到後端要畫面資料",
                        myStartDate: "2021-04-07",
                        myDueDate: "2021-04-17",
                        myStatus: 0 //未完成:0,進行中:1,已完成:2,其他狀態待擴充
                    }
                    //將date1放回dataList中
                    _self.dataList.push(date1);


                    //將資料寫入date2陣列中(進行中資料)
                    let date2 = {
                        myTitle: "切版",
                        myDetail: "使用HTML拉出ToDoList的畫面",
                        myStartDate: "2021-04-06",
                        myDueDate: "2021-04-07",
                        myStatus: 1 //未完成:0,進行中:1,已完成:2,其他狀態待擴充
                    }
                    //將date1放回dataList中
                    _self.dataList.push(date2);


                    //將資料寫入date3陣列中(已完成資料)
                    let date3 = {
                        myTitle: "建立專案",
                        myDetail: "建一個MVC的專案檔",
                        myStartDate: "2021-04-01",
                        myDueDate: "2021-04-06",
                        myStatus: 2 //未完成:0,進行中:1,已完成:2,其他狀態待擴充
                    }
                    //將date1放回dataList中
                    _self.dataList.push(date3);


                    //將資料寫入date4陣列中(未完成資料)
                    let date4 = {
                        myTitle: "存取資料",
                        myDetail: "使用local Storgae 存取資料",
                        myStartDate: "2021-04-07",
                        myDueDate: "2021-04-17",
                        myStatus: 0 //未完成:0,進行中:1,已完成:2,其他狀態待擴充
                    }
                    //將date1放回dataList中
                    _self.dataList.push(date4);

                    //將資料寫入date5陣列中(未完成資料)
                    let date5 = {
                        myTitle: "新增功能",
                        myDetail: "增加新增按鈕，並彈出視窗，來新增資料",
                        myStartDate: "2021-04-07",
                        myDueDate: "2021-04-17",
                        myStatus: 0 //未完成:0,進行中:1,已完成:2,其他狀態待擴充
                    }
                    //將date1放回dataList中
                    _self.dataList.push(date5);

                    //將資料寫入date6陣列中(未完成資料)
                    let date6 = {
                        myTitle: "更改狀態功能",
                        myDetail: "點選畫面上的按鈕並修改完成的狀態",
                        myStartDate: "2021-04-07",
                        myDueDate: "2021-04-17",
                        myStatus: 0 //未完成:0,進行中:1,已完成:2,其他狀態待擴充
                    }
                    //將date1放回dataList中
                    _self.dataList.push(date6);
                },

            },
            //監聽屬性(畫面上會因為發生某個事件或參數的變化，而導致畫面的UI或參數需要跟隨著變化時可使用)
            computed: {
                //過濾未完成的資料
                notFinishDataList: function () {
                    _self = this;
                    //這邊使用filter做陣列的過濾
                    //filter用法 陣列.filter(變數1 =>變數1.陣列的物件 == 條件 )
                    return _self.dataList.filter(item => item.myStatus == 0);
                },

                //過濾進行中的資料
                DoingDataList: function () {
                    _self = this;
                    //這邊使用filter做陣列的過濾
                    //filter用法 陣列.filter(變數1 =>變數1.陣列的物件 == 條件 )
                    return _self.dataList.filter(item => item.myStatus == 1);
                },

                //過濾已完成的資料
                isFinishDataList: function () {
                    _self = this;
                    //這邊使用filter做陣列的過濾
                    //filter用法 陣列.filter(變數1 =>變數1.陣列的物件 == 條件 )
                    return _self.dataList.filter(item => item.myStatus == 2);
                },

            }
        })

    </script>
</body>
</html>

VueByAspNet_Mvc/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

VueByAspNet_Mvc/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

VueByAspNet_Mvc/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

VueByAspNet_Mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - 我的 ASP.NET 應用程式</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("應用程式名稱", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("首頁", "Index", "Home")</li>
                    <li>@Html.ActionLink("關於", "About", "Home")</li>
                    <li>@Html.ActionLink("連絡人", "Contact", "Home")</li>
                    <li>@Html.ActionLink("計畫表", "toDoList", "Demo")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - 我的 ASP.NET 應用程式</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>